### ISSUE TITLE
Compling Module.cpp

### ISSUE THREAD

**Issue by kzts** [lornat75/Teaching#1]
Hi! @lornat75 
I tried compling `/Teaching/code/wbi/Module.cpp` using cmake.
And I got following messages.

```
CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "FindyarpWholeBodyInterface.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "yarpWholeBodyInterface", but CMake did not find one.

  Could not find a package configuration file provided by
  "yarpWholeBodyInterface" with any of the following names:

    yarpWholeBodyInterfaceConfig.cmake
    yarpwholebodyinterface-config.cmake

  Add the installation prefix of "yarpWholeBodyInterface" to
  CMAKE_PREFIX_PATH or set "yarpWholeBodyInterface_DIR" to a directory
  containing one of the above files.  If "yarpWholeBodyInterface" provides a
  separate development package or SDK, be sure it has been installed.
```

It seems that I don't have `yarpWholeBodyInterfaceConfig.cmake` and `yarpwholebodyinterface-config.cmake`.
How do I get this files or fix this error?

**Comment by francesco-romano** [comment]
A requirement for this project is [yarpWholeBodyInterface](https://github.com/robotology/yarp-wholebodyinterface).
You can install it by using the codyco-superbuild: https://github.com/robotology/codyco-superbuild

**Comment by kzts** [comment]
Thank you @francesco-romano !
I forgot modified `.bashrc`.
I solved this problem, using the codyco-superbuild again and modifying `.bashrc`.
