### ISSUE TITLE
Whole body interface example

### ISSUE THREAD

**Issue by kzts** [lornat75/Teaching#2]
I complied `lornat75/Teaching/code/wbi` using `cmake` and executed `WBI_example`.
And I got following error messages.

```
No WBI configuration file found.
Module failed to open
```

Should I set some path? Or did I put file wrong place?

**Comment by francesco-romano** [comment]
Hi @kzts 
I added a bit of documentation here: https://github.com/lornat75/Teaching/tree/master/code/wbi

Can you check if that is enough?

**Comment by kzts** [comment]
Hi @francesco-romano 
Thank you for your rapid reply and the documentation!
I could execute `WBI_example` and got following error messages.
Should I modify `YARP_DATA_DIRS`?

```
[INFO]created device <remote_controlboard>. See C++ class yarp::dev::RemoteControlBoard for documentation.
||| finding file [model.urdf]
||| checking [/home/k-tanaka/Code/lornat75/Teaching/code/wbi/build/model.urdf] (pwd)
||| checking [/home/k-tanaka/.config/yarp/robots/default] (robot YARP_CONFIG_HOME)
||| checking [/home/k-tanaka/.local/share/yarp/robots/default] (robot YARP_DATA_HOME)
||| checking [/etc/xdg/xdg-ubuntu/yarp/robots/default] (robot YARP_CONFIG_DIRS)
||| checking [/usr/share/upstart/xdg/yarp/robots/default] (robot YARP_CONFIG_DIRS)
||| checking [/etc/xdg/yarp/robots/default] (robot YARP_CONFIG_DIRS)
||| checking [robots/default] (robot YARP_DATA_DIRS)
||| checking [/home/k-tanaka/Code/codyco-superbuild/build/install/share/codyco/robots/default] (robot YARP_DATA_DIRS)
||| checking [config/path.d] (robot path.d YARP_DATA_DIRS)
||| checking [/home/k-tanaka/Code/codyco-superbuild/build/install/share/codyco/config/path.d] (robot path.d YARP_DATA_DIRS)
||| checking [/home/k-tanaka/.config/yarp/model.urdf] (YARP_CONFIG_HOME)
||| checking [/home/k-tanaka/.local/share/yarp/model.urdf] (YARP_DATA_HOME)
||| checking [/etc/xdg/xdg-ubuntu/yarp/model.urdf] (YARP_CONFIG_DIRS)
||| checking [/usr/share/upstart/xdg/yarp/model.urdf] (YARP_CONFIG_DIRS)
||| checking [/etc/xdg/yarp/model.urdf] (YARP_CONFIG_DIRS)
||| checking [model.urdf] (YARP_DATA_DIRS)
||| checking [/home/k-tanaka/Code/codyco-superbuild/build/install/share/codyco/model.urdf] (YARP_DATA_DIRS)
||| did not find model.urdf
Error document empty.[ERR] Could not parse string to urdf::ModelInterface
DynTree constructor: Could not generate robot model from file   and extract kdl tree
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

```

**Comment by francesco-romano** [comment]
Ok.. maybe I understood

Can you try to launch the example from the main folder, i.e.

```
./build/WBI_example --wbi_config_file bi-config.ini
```

If this work I'll update the readme.

Modifying `YARP_DATA_DIRS` is an option, but it does not make any sense in this simplified example.

**Comment by kzts** [comment]
Thank you @francesco-romano !
I tried `./build/WBI_example --wbi_config_file bi-config.ini` and executed `EBI_example` without error message.

I used gazebo and a icub model https://github.com/robotology-playground/icub-gazebo/tree/master/icub because `/Teahing/code/wbi` doesn't include `meshes` directory.
This icub model bended its hip and falled in the gazebo simulator.
Which should I select robot model and simulator?

**Comment by francesco-romano** [comment]
Ok, so I'll update the readme.

Yes. The code in the wbi folder is intended to be a controller, not a full-simulation environment. Gazebo is a choice.

You can try to use the icub_fixed model. Probably the gains must be tuned anyway.

**Comment by kzts** [comment]
I used the `iCub (fixed)` model on the Gazebo. Then, codes seemed to be executed correctly.
Thank you very musch @francesco-romano !
